In [44]:
#dependencies
import csv
import pandas as pd
import warnings
warnings.simplefilter("error")

In [45]:
db_1906 = pd.read_csv(r"C:\Users\thevc\OneDrive\Desktop\citibikeviz\201906-citibike-tripdata.csv")
db_1912 = pd.read_csv(r"C:\Users\thevc\OneDrive\Desktop\citibikeviz\201912-citibike-tripdata.csv")
db_2006 = pd.read_csv(r"C:\Users\thevc\OneDrive\Desktop\citibikeviz\202006-citibike-tripdata.csv")
db_2012 = pd.read_csv(r"C:\Users\thevc\OneDrive\Desktop\citibikeviz\202012-citibike-tripdata.csv")

In [46]:
citibikedata_19 = pd.concat([db_1906,db_1912])

In [47]:
citibikedata_19.isnull().any()

tripduration               False
starttime                  False
stoptime                   False
start station id           False
start station name         False
start station latitude     False
start station longitude    False
end station id             False
end station name           False
end station latitude       False
end station longitude      False
bikeid                     False
usertype                   False
birth year                 False
gender                     False
dtype: bool

In [48]:
citibikedata_19.tail()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
955205,93,2019-12-31 23:58:18.0160,2019-12-31 23:59:51.6360,3141,1 Ave & E 68 St,40.765005,-73.958185,3142,1 Ave & E 62 St,40.761227,-73.960940,28734,Subscriber,1985,2
955206,786,2019-12-31 23:58:59.8960,2020-01-01 00:12:06.3460,490,8 Ave & W 33 St,40.751551,-73.993934,513,W 56 St & 10 Ave,40.768254,-73.988639,41418,Subscriber,1991,1
955207,351,2019-12-31 23:59:03.6950,2020-01-01 00:04:54.8730,3349,Grand Army Plaza & Plaza St West,40.672968,-73.970880,3368,5 Ave & 3 St,40.672815,-73.983524,27746,Subscriber,1935,2
955208,1571,2019-12-31 23:59:21.3610,2020-01-01 00:25:32.9420,252,MacDougal St & Washington Sq,40.732264,-73.998522,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,28506,Subscriber,1980,1
955209,310,2019-12-31 23:59:55.2960,2020-01-01 00:05:05.7270,3351,E 102 St & 1 Ave,40.786995,-73.941648,3379,E 103 St & Lexington Ave,40.790305,-73.947558,21013,Subscriber,1969,0

In [49]:
citibikedata_final19=citibikedata_19.dropna(axis=0).reset_index(drop=True)
citibikedata_final19.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602,31 Ave & 34 St,40.763154,-73.920827,3570,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054,Greene Ave & Throop Ave,40.689493,-73.942061,3781,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229,Great Jones St,40.727434,-73.993790,326,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771,McKibbin St & Bogart St,40.706237,-73.933871,3016,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441,E 52 St & 2 Ave,40.756014,-73.967416,3159,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1

In [50]:
citibikedata_final19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3080580 entries, 0 to 3080579
Data columns (total 15 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tripduration             int64
 1   starttime                object
 2   stoptime                 object
 3   start station id         int64
 4   start station name       object
 5   start station latitude   float64
 6   start station longitude  float64
 7   end station id           int64
 8   end station name         object
 9   end station latitude     float64
 10  end station longitude    float64
 11  bikeid                   int64
 12  usertype                 object
 13  birth year               int64
 14  gender                   int64
dtypes: float64(4), int64(6), object(5)
memory usage: 352.5+ MB

In [63]:
citibikedata_final19.to_csv("citibikeTripdata2019.csv",index=False)

In [64]:
citibikedata_20 = pd.concat([db_2006,db_2012])

In [65]:
citibikedata_20.isnull().any()

tripduration               False
starttime                  False
stoptime                   False
start station id           False
start station name         False
start station latitude     False
start station longitude    False
end station id             False
end station name           False
end station latitude       False
end station longitude      False
bikeid                     False
usertype                   False
birth year                 False
gender                     False
dtype: bool

In [66]:
citibikedata_20.tail()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1088924,2045,2020-12-31 23:58:21.7040,2021-01-01 00:32:27.1570,526,E 33 St & 5 Ave,40.747659,-73.984907,3614,Crescent St & 30 Ave,40.768692,-73.924957,36467,Subscriber,1994,1
1088925,288,2020-12-31 23:58:37.8400,2021-01-01 00:03:26.3250,3307,West End Ave & W 94 St,40.794165,-73.974124,3383,Cathedral Pkwy & Broadway,40.804213,-73.966991,47749,Subscriber,1969,0
1088926,152,2020-12-31 23:58:52.8090,2021-01-01 00:01:25.6720,3510,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3518,Lenox Ave & W 126 St,40.808442,-73.945209,48691,Customer,1969,0
1088927,654,2020-12-31 23:59:55.9550,2021-01-01 00:10:50.6050,4073,W 51 St & Rockefeller Plaza,40.759700,-73.978082,500,Broadway & W 51 St,40.762288,-73.983362,49564,Subscriber,1994,1
1088928,2589,2020-12-31 23:59:57.4070,2021-01-01 00:43:06.4490,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47364,Customer,1969,0

In [67]:
citibikedata_final20=citibikedata_20.dropna(axis=0).reset_index(drop=True)
citibikedata_final20.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2

In [69]:
citibikedata_final20.to_csv("citibikeTripdata2020.csv",index=False)